/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SyncJobsRouteImport } from './routes/sync-jobs'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as QueuesRouteImport } from './routes/queues'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ObjectsRouteImport } from './routes/objects'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FlowsRouteImport } from './routes/flows'
import { Route as DrMonitoringRouteImport } from './routes/dr-monitoring'
import { Route as DrControlRouteImport } from './routes/dr-control'
import { Route as DivisionsRouteImport } from './routes/divisions'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConfigureRouteImport } from './routes/configure'
import { Route as BackupsRouteImport } from './routes/backups'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SyncJobsRoute = SyncJobsRouteImport.update({
  id: '/sync-jobs',
  path: '/sync-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const QueuesRoute = QueuesRouteImport.update({
  id: '/queues',
  path: '/queues',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjectsRoute = ObjectsRouteImport.update({
  id: '/objects',
  path: '/objects',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowsRoute = FlowsRouteImport.update({
  id: '/flows',
  path: '/flows',
  getParentRoute: () => rootRouteImport,
} as any)
const DrMonitoringRoute = DrMonitoringRouteImport.update({
  id: '/dr-monitoring',
  path: '/dr-monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const DrControlRoute = DrControlRouteImport.update({
  id: '/dr-control',
  path: '/dr-control',
  getParentRoute: () => rootRouteImport,
} as any)
const DivisionsRoute = DivisionsRouteImport.update({
  id: '/divisions',
  path: '/divisions',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigureRoute = ConfigureRouteImport.update({
  id: '/configure',
  path: '/configure',
  getParentRoute: () => rootRouteImport,
} as any)
const BackupsRoute = BackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/backups': typeof BackupsRoute
  '/configure': typeof ConfigureRoute
  '/contact': typeof ContactRoute
  '/divisions': typeof DivisionsRoute
  '/dr-control': typeof DrControlRoute
  '/dr-monitoring': typeof DrMonitoringRoute
  '/flows': typeof FlowsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/objects': typeof ObjectsRoute
  '/pricing': typeof PricingRoute
  '/queues': typeof QueuesRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/sync-jobs': typeof SyncJobsRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/backups': typeof BackupsRoute
  '/configure': typeof ConfigureRoute
  '/contact': typeof ContactRoute
  '/divisions': typeof DivisionsRoute
  '/dr-control': typeof DrControlRoute
  '/dr-monitoring': typeof DrMonitoringRoute
  '/flows': typeof FlowsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/objects': typeof ObjectsRoute
  '/pricing': typeof PricingRoute
  '/queues': typeof QueuesRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/sync-jobs': typeof SyncJobsRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/backups': typeof BackupsRoute
  '/configure': typeof ConfigureRoute
  '/contact': typeof ContactRoute
  '/divisions': typeof DivisionsRoute
  '/dr-control': typeof DrControlRoute
  '/dr-monitoring': typeof DrMonitoringRoute
  '/flows': typeof FlowsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/objects': typeof ObjectsRoute
  '/pricing': typeof PricingRoute
  '/queues': typeof QueuesRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/sync-jobs': typeof SyncJobsRoute
  '/users': typeof UsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/backups'
    | '/configure'
    | '/contact'
    | '/divisions'
    | '/dr-control'
    | '/dr-monitoring'
    | '/flows'
    | '/forgot-password'
    | '/login'
    | '/logs'
    | '/objects'
    | '/pricing'
    | '/queues'
    | '/register'
    | '/settings'
    | '/skills'
    | '/sync-jobs'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/backups'
    | '/configure'
    | '/contact'
    | '/divisions'
    | '/dr-control'
    | '/dr-monitoring'
    | '/flows'
    | '/forgot-password'
    | '/login'
    | '/logs'
    | '/objects'
    | '/pricing'
    | '/queues'
    | '/register'
    | '/settings'
    | '/skills'
    | '/sync-jobs'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/backups'
    | '/configure'
    | '/contact'
    | '/divisions'
    | '/dr-control'
    | '/dr-monitoring'
    | '/flows'
    | '/forgot-password'
    | '/login'
    | '/logs'
    | '/objects'
    | '/pricing'
    | '/queues'
    | '/register'
    | '/settings'
    | '/skills'
    | '/sync-jobs'
    | '/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  BackupsRoute: typeof BackupsRoute
  ConfigureRoute: typeof ConfigureRoute
  ContactRoute: typeof ContactRoute
  DivisionsRoute: typeof DivisionsRoute
  DrControlRoute: typeof DrControlRoute
  DrMonitoringRoute: typeof DrMonitoringRoute
  FlowsRoute: typeof FlowsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  LogsRoute: typeof LogsRoute
  ObjectsRoute: typeof ObjectsRoute
  PricingRoute: typeof PricingRoute
  QueuesRoute: typeof QueuesRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRoute
  SkillsRoute: typeof SkillsRoute
  SyncJobsRoute: typeof SyncJobsRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sync-jobs': {
      id: '/sync-jobs'
      path: '/sync-jobs'
      fullPath: '/sync-jobs'
      preLoaderRoute: typeof SyncJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queues': {
      id: '/queues'
      path: '/queues'
      fullPath: '/queues'
      preLoaderRoute: typeof QueuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objects': {
      id: '/objects'
      path: '/objects'
      fullPath: '/objects'
      preLoaderRoute: typeof ObjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flows': {
      id: '/flows'
      path: '/flows'
      fullPath: '/flows'
      preLoaderRoute: typeof FlowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dr-monitoring': {
      id: '/dr-monitoring'
      path: '/dr-monitoring'
      fullPath: '/dr-monitoring'
      preLoaderRoute: typeof DrMonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dr-control': {
      id: '/dr-control'
      path: '/dr-control'
      fullPath: '/dr-control'
      preLoaderRoute: typeof DrControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/divisions': {
      id: '/divisions'
      path: '/divisions'
      fullPath: '/divisions'
      preLoaderRoute: typeof DivisionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configure': {
      id: '/configure'
      path: '/configure'
      fullPath: '/configure'
      preLoaderRoute: typeof ConfigureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backups': {
      id: '/backups'
      path: '/backups'
      fullPath: '/backups'
      preLoaderRoute: typeof BackupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  BackupsRoute: BackupsRoute,
  ConfigureRoute: ConfigureRoute,
  ContactRoute: ContactRoute,
  DivisionsRoute: DivisionsRoute,
  DrControlRoute: DrControlRoute,
  DrMonitoringRoute: DrMonitoringRoute,
  FlowsRoute: FlowsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  LogsRoute: LogsRoute,
  ObjectsRoute: ObjectsRoute,
  PricingRoute: PricingRoute,
  QueuesRoute: QueuesRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
  SkillsRoute: SkillsRoute,
  SyncJobsRoute: SyncJobsRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
